language: php
dist: xenial
php:
  - '7.1'
  - '7.2'
  - '7.3'
matrix:
  include:
    - php: '7.1'
      addons:
        apt:
          packages:
            - php7.1-ssh2
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v